Revert some of "Don't truncate std{out,err} in JUnit results (#172)" (#173)
This reverts portions of commit 5162a9ca03b2020a4d3371c5d37d8ccb294a0f05
that converted defs to types and primitives as that was causing:

org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[]' with class 'java.util.ArrayList' to class 'java.util.Map' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.Map()

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>